# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crpn4r3lb1p72fv7v101/dds_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2026-03-15-r28"

containerPort: 5000

config:
  KAFKA_HOST: "rc1a-7j9hcd9hpgvn9jjq.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_consumer"
  KAFKA_CONSUMER_PASSWORD: "Kudry@shka!"
  KAFKA_CONSUMER_GROUP: "desperprox_dds"
  KAFKA_SOURCE_TOPIC: "stg-service-orders"
  KAFKA_DDS_SERVICE_ORDERS_TOPIC: "dds-service-orders"

  PG_WAREHOUSE_HOST: "rc1b-57chu90f89s86s5t.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "db_user"
  PG_WAREHOUSE_PASSWORD: "Kudry@shka!"

  REDIS_HOST: "c-c9q72frkmlqn2vgfsshe.rw.mdb.yandexcloud.net"
  REDIS_PORT: "6380"
  REDIS_PASSWORD: "Kudry@shka!"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
